variables:
  REPO_DIR: "/home/dashboard/HCCDashboard"

stages:
  - deploy
  - sync-to-github

deploy:
  stage: deploy
  environment:
    name: production
    url: https://viz.unl.edu:3030/hcc
  only:
    - master
  tags:
    - viz
  before_script:
    - eval $(ssh-agent -s) > /dev/null
    - mkdir -p ~/.ssh
    - chown 700 ~/.ssh
    - echo $SSH_KNOWN_HOSTS > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - ssh-add <(echo "$SSH_PRIVATE_KEY" | base64 --decode)
  script:
    - cd $REPO_DIR
    - git checkout master
    - git fetch
    - git checkout $CI_COMMIT_SHA
    - pkill -HUP -u dashboard -f /usr/local/bin/thin

sync-to-github:
  stage: sync-to-github
  tags:
    - docker
  image: unlhcc/crane-build-el6
  allow_failure: yes
  only:
    - master
  script:
    - eval $(ssh-agent -s) > /dev/null
    - mkdir -p ~/.ssh
    - chown 700 ~/.ssh
    - echo $GITHUB_SSH_KNOWN_HOSTS > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - ssh-add <(echo "$GITHUB_SSH_DEPLOY_PKEY" | base64 --decode)
    - git config user.name "HCC Gitlab CI"
    - git config user.email "hcc-support@unl.edu"
    - git checkout master
    - git remote add github git@github.com:unlhcc/HCCDashboard.git
    - git push github +master
